# Configuration file for LLM (Large Language Model) settings
# This file contains various settings for the LLM environment, agent behavior, partitioning, application,
# rendering, intervention system, and enhanced delegation.

# Environment settings
original_map_size: 64               # Original map size for the environment

# Agent behavior
force_delegate_to_rl: true         # Force delegation to RL agent for testing
force_delegate_to_llm: false        # Force delegation to LLM agent for testing
llm_call_frequency: 15              # Number of steps between LLM calls

# Partitioning settings  
use_manual_partitioning: true      # Use manual partitioning 
use_random_partitioning: false      # Use random partitioning 
max_num_partitions: 1               # Maximum number of partitions for LLM (Partitioning Agent)
use_exact_number_of_partitions: false # Use exact number of partitions for LLM (Partitioning Agent)
use_image_prompt: true              # Use image prompt for LLM (Partitioning Agent)

# Application settings
app_name: "ExcavatorGameApp"        # Application name for ADK
user_id: "user_1"                   # User ID for ADK  
session_id: "session_001"           # Session ID for ADK
compute_bench_stats: true           # Compute and print benchmark statistics

# Rendering settings
grid_rendering: false               # Use grid rendering for partitions
use_rendering: true                 # Use rendering for the environment
use_display: true                   # Use display for the environment
visualize_partitions: true          # Visualize partitions
save_video: false                    # Save video of the environment
fps: 10                             # Frames per second for video rendering

# Intervention System Settings
enable_intervention: false          # Enable intervention system
intervention_check_frequency: 5     # Check every N steps
stuck_detection_window: 10          # Number of recent steps to analyze
min_reward_threshold: 0.001         # Minimum reward expected in window
intervention_cooldown: 3            # Minimum steps between interventions

# Enhanced delegation
enhanced_delegation_prompts: false  # Use enhanced delegation prompts
include_stuck_context: false        # Include stuck context in prompts  